Cleaned up the live-scripts

diff --git a/generation_system/live/initramfs-tools/live_scripts/live-premount/local b/generation_system/live/initramfs-tools/live_scripts/live-premount/local
--- a/generation_system/live/initramfs-tools/live_scripts/live-premount/local
+++ b/generation_system/live/initramfs-tools/live_scripts/live-premount/local
@@ -1,6 +1,6 @@
 #!/bin/sh
 # Search the image in the local disks
-PREREQ="network"
+PREREQ="tmpfs"
 
 prereqs()
 {
@@ -32,8 +32,8 @@ for device in /sys/block/* ; do
 done
 
 
-modprobe -q isofs
-mkdir -p /mnt/dev
+modprobe -q isofs >> /tmp/initramfs.debug 2>&1
+mkdir -p /mnt/dev >> /tmp/initramfs.debug 2>&1
 found=n
 for disk in $disks; do
 	mount -t auto -o ro /dev/$disk /mnt/dev >> /tmp/initramfs.debug 2>&1
@@ -45,9 +45,11 @@ for disk in $disks; do
 	fi
 done
 if [ x${found} = xy ]; then
-	echo "LOCAL: Montada la imagen" >> /tmp/initramfs.debug
+	echo "LOCAL: image mounted" >> /tmp/initramfs.debug
+	exit 0
 else
-	echo "LOCAL: ERROR -> NO montada la imagen" >> /tmp/initramfs.debug
+	echo "LOCAL: ERROR -> image non mounted" >> /tmp/initramfs.debug
+	exit 1
 fi
 
 
diff --git a/generation_system/live/initramfs-tools/live_scripts/live-premount/setup_image b/generation_system/live/initramfs-tools/live_scripts/live-premount/setup_image
--- a/generation_system/live/initramfs-tools/live_scripts/live-premount/setup_image
+++ b/generation_system/live/initramfs-tools/live_scripts/live-premount/setup_image
@@ -16,18 +16,18 @@ prereqs)
 	;;
 esac
 
-echo "SETUP_IMAGE: Antes de cargar los modulos squashfs y loop" >> /messages.txt
 # Just to be sure
-modprobe -q squashfs
-modprobe -q loop
+modprobe -q squashfs >> /tmp/initramfs.debug 2>&1
+modprobe -q loop >> /tmp/initramfs.debug 2>&1
 
 IMAGE=/mnt/image
-mkdir -p ${IMAGE}
+mkdir -p ${IMAGE} >> /tmp/initramfs.debug 2>&1
 
-echo "SETUP_IMAGE: Antes de montar la imagen" >> /messages.txt
-mount -o loop -t squashfs /mnt/dev/META/META.squashfs $IMAGE
+mount -o loop -t squashfs /mnt/dev/META/META.squashfs $IMAGE >> /tmp/initramfs.debug 2>&1
 if [ $? = 0 ]; then
-	echo "SETUP_IMAGE: Montada la imagen" >> /messages.txt
+	echo "SETUP_IMAGE: image mounted"  >> /tmp/initramfs.debug 2>&1
+	exit 0
 else
-	echo "SETUP_IMAGE: ERROR -> NO montada la imagen" >> /messages.txt
+	echo "SETUP_IMAGE: ERROR -> image non mounted"  >> /tmp/initramfs.debug 2>&1
+	exit 1
 fi
